import { GraphicsData } from "../types/graphics";

export const parseGraphicsArray = (data: any[]): GraphicsData => {
  let i = 0;

  return {
    stepIndex: data[i++],
    status: data[i++],
    session: data[i++],
    currentLapTime: data[i++],
    lastLapTime: data[i++],
    bestLapTime: data[i++],
    split: data[i++],
    completedLaps: data[i++],
    position: data[i++],
    currentLapTimeMs: data[i++],
    lastLapTimeMs: data[i++],
    bestLapTimeMs: data[i++],
    sessionTimeLeft: data[i++],
    distanceTraveled: data[i++],
    isInPit: !!data[i++],
    currentSectorIndex: data[i++],
    lastSectorTimeMs: data[i++],
    numberOfLaps: data[i++],
    tyreCompoundName: data[i++],
    replayTimeMultiplier: data[i++],
    normalizedCarPosition: data[i++],
    carsOnTrack: data[i++],
    carCoordinates: Array.from({ length: 60 }, () => {
      const x = data[i++];
      const y = data[i++];
      const z = data[i++];
      return [x, y, z] as [number, number, number];
    }).filter(
      (coords) => coords[0] !== 0 && coords[1] !== 0 && coords[2] !== 0
    ),
    carID: Array.from({ length: 60 }, () => data[i++]).filter((id) => id !== 0),
    playerCarID: data[i++],
    penaltyTime: data[i++],
    flag: data[i++],
    penalty: data[i++],
    isIdealLineOn: !!data[i++],
    isInPitLane: !!data[i++],
    surfaceGrip: data[i++],
    isMandatoryPitDone: !!data[i++],
    windSpeed: data[i++],
    windDirection: data[i++],
    isSetupMenuVisible: !!data[i++],
    mainDisplayIndex: data[i++],
    secondaryDisplayIndex: data[i++],
    tractionControlLevel: data[i++],
    tractionControlCut: data[i++],
    engineMap: data[i++],
    abs: data[i++],
    averageFuelConsumptionPerLap: data[i++],
    rainLights: data[i++],
    flashingLights: data[i++],
    lightsStage: data[i++],
    exhaustTemperature: data[i++],
    wiperLV: data[i++],
    driverStintTotalTimeLeft: data[i++],
    driverStintTimeLeft: data[i++],
    rainTyres: data[i++],
    sessionIndex: data[i++],
    usedFuel: data[i++],
    deltaLapTime: data[i++],
    iDeltaLapTime: data[i++],
    estimatedLapTime: data[i++],
    iEstimatedLapTime: data[i++],
    isDeltaPositive: !!data[i++],
    iSplit: data[i++],
    isValidLap: !!data[i++],
    fuelEstimatedLaps: data[i++],
    trackStatus: data[i++],
    missingMandatoryPits: data[i++],
    clock: data[i++],
    directionLightsLeft: !!data[i++],
    directionLightsRight: !!data[i++],
    globalYellow: !!data[i++],
    globalYellow1: !!data[i++],
    globalYellow2: !!data[i++],
    globalYellow3: !!data[i++],
    globalWhite: !!data[i++],
    globalGreen: !!data[i++],
    globalChequered: !!data[i++],
    globalRed: !!data[i++],
    mfdTyreSet: data[i++],
    mfdFuelToAdd: data[i++],
    mfdTyrePressureLF: data[i++],
    mfdTyrePressureRF: data[i++],
    mfdTyrePressureLR: data[i++],
    mfdTyrePressureRR: data[i++],
    trackGripStatus: data[i++],
    rainIntensity: data[i++],
    rainIntensityIn10min: data[i++],
    rainIntensityIn30min: data[i++],
    currentTyreSet: data[i++],
    strategyTyreSet: data[i++],
    gapAhead: data[i++],
    gapBehind: data[i++],
  };
};
