import { GraphicsData } from "../types/graphics";

export const parseGraphicsArray = (data: any[]): GraphicsData => {
  let i = 0;

  return {
    stepIndex: data[i++],
    status: data[i++],
    session: data[i++],
    currentLapTime: data[i++],
    lastLapTime: data[i++],
    bestLapTime: data[i++],
    split: data[i++],
    completedLaps: data[i++],
    position: data[i++],
    currentLapTimeMs: data[i++],
    lastLapTimeMs: data[i++],
    bestLapTimeMs: data[i++],
    sessionTimeLeft: data[i++],
    distanceTraveled: data[i++],
    isInPit: !!data[i++],
    currentSectorIndex: data[i++],
    lastSectorTimeMs: data[i++],
    numberOfLaps: data[i++],
    tyreCompoundName: data[i++],
    replayTimeMultiplier: data[i++],
    normalizedCarPosition: data[i++],
    carsOnTrack: data[i++],
    carCoordinates: Array.from({ length: 60 }, () => [
      data[i++],
      data[i++],
      data[i++],
    ]),
    carID: Array.from({ length: 60 }, () => data[i++]),
    playerCarID: data[i++],
    penaltyTime: data[i++],
    flag: data[i++],
    penalty: data[i++],
    isIdealLineOn: !!data[i++],
    isInPitLane: !!data[i++],
    surfaceGrip: data[i++],
    isMandatoryPitDone: !!data[i++],
    windSpeed: data[i++],
    windDirection: data[i++],
    isSetupMenuVisible: !!data[i++],
    mainDisplayIndex: data[i++],
    secondaryDisplayIndex: data[i++],
    tractionControlLevel: data[i++],
    tractionControlCut: data[i++],
    engineMap: data[i++],
    abs: data[i++],
    averageFuelConsumptionPerLap: data[i++],
    rainLights: data[i++],
    flashingLights: data[i++],
    lightsStage: data[i++],
    exhaustTemperature: data[i++],
    wiperLV: data[i++],
    driverStintTotalTimeLeft: data[i++],
    driverStintTimeLeft: data[i++],
    rainTyres: data[i++],
  };
};
